baseURL = 'https://omadacraft.net/'
languageCode = 'de-de'
title = 'OmadaCraft Network'
theme = 'omadacraft'

[menus]
  [[menus.main]]
    name = 'Home'
    url = '/'
    weight = 10
  [[menus.main]]
    name = 'Spielmodi'
    url = '/#gamemodes'
    weight = 20
  [[menus.main]]
    name = 'Status'
    url = '/status'
    weight = 30
  [[menus.main]]
    name = 'Team'
    url = '/team'
    weight = 40
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true 