baseURL = 'https://omadacraft.net/'
languageCode = 'de-de'
title = 'OmadaCraft Network'
theme = 'omadacraft'

[menus]
  [[menus.main]]
    name = 'Home'
    url = '/'
    weight = 10
  [[menus.main]]
    name = 'Status'
    url = '/status'
    weight = 20
  [[menus.main]]
    name = 'Team'
    url = '/team'
    weight = 30
  [[menus.main]]
    name = 'FAQ'
    url = '/faq'
    weight = 40
  [[menus.main]]
    name = 'Vote'
    url = '/vote'
    weight = 50
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true 
[outputs]
  home = ["HTML", "RSS", "JSON"]